# frozen_string_literal: true

# This file is auto-generated by Jekyll Auth
# It tells Heroku how to launch our site

require 'rack/jekyll'
require "jekyll-auth"
require 'yaml'

run JekyllAuth.site
run Rack::Jekyll.new
