# frozen_string_literal: true

# This file is auto-generated by Jekyll Auth
# Feel free to add additional Rake tasks so long as
# `rake assets:precompile` continues to generate the jekyll site

namespace :assets do
  task :precompile do
    puts `bundle exec jekyll build`
  end
  
  task :precompile do
    sh "bundle exec jekyll-auth build"
  end
end
